# List of all source files
# Generated by CMake
set(sources
Source/EnumClassHash.h
Source/KeyHook.cpp
Source/KeyHook.h
Source/Keys.cpp
Source/Keys.h
Source/MouseKeyMapper.cpp
Source/MouseKeyMapper.h
Source/OSWrap.cpp
Source/OSWrap.h
Source/ScanCodes.cpp
Source/ScanCodes.h
Source/main.cpp
)
